from enum import Enum

class PROFESSION_CATEGORY(str, Enum):
    TECHNOLOGY = "TECHNOLOGY"
    MEDICINE = "MEDICINE"
    EDUCATION = "EDUCATION"
    FINANCE = "FINANCE"
    ENGINEERING = "ENGINEERING"
    ARTS = "ARTS"
    BUSINESS = "BUSINESS"
    LAW = "LAW"
    SCIENCE = "SCIENCE"
    SOCIAL_SCIENCES = "SOCIAL_SCIENCES"
    GOVERNMENT = "GOVERNMENT"
    AGRICULTURE = "AGRICULTURE"

class POPULARITY(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
